server:
  port: 8004
  compression:
    enabled: true
spring:
  cloud:
    refresh:
      enabled: false
  datasource:
    hikari:
      maximum-pool-size: 4
#    url: jdbc:mariadb://192.168.0.133:3306/localhost
#    driver-class-name: org.mariadb.jdbc.Driver
    ##    git push 시 아래 주석 처리
    #    url: jdbc:log4jdbc:mariadb://14.41.2.189:13306/neos_default
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    username: root
#    password: 976500
    url: jdbc:mariadb://14.41.2.189:13306/neos_default
    driver-class-name: org.mariadb.jdbc.Driver
    username: neos
    password: neos

#Klago:
#  mode: live
#  dbType: mariadb
#  event:
#    url: https://dev.amaranth10.co.kr
#  Sign:
#    Value: 4edec53cebbe603e34458532505c45
#  groupware:
#    domain: https://dev.amaranth10.co.kr
#  Mqtt:
#    ip: 14.41.2.189
#    id: event
#    port : 11887
#    node : bizboxA@127.0.0.1
#    password: 7c02fcc9-33dd-4d9d-a9ab-3779c362eb86_klagoDev
#    authYn: Y
#    encryptionYn: Y
#    encryptionVer: 1
#    sslYn : N
#    keyStoreType : PEM
#  redis:
#    ip: 14.41.2.189
#    port: 16384
#    password: 1234
#  elasticsearch:
#    hosts: 14.41.2.189
#    port: 19204
logging:
  config: ./log4j2.xml
